# -*- coding: utf-8 -*-
"""Thread.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14CY692l6LXu9QmQThsJGjzWbtZTM5wms
"""

#https://realpython.com/intro-to-python-threading/#starting-a-thread
import threading
import time

def funcao_da_thread(nome):
    print("Sou o a thread ",nome, " e vou dormir")
    time.sleep(2)
    print("Sou a thread ", nome, " e terminei")
    while True:
      print("sou o a Thread" , nome)
      time.sleep(2)

if __name__ == "__main__": #função principal
    c = 0
    while c<10:
        t = threading.Thread(target=funcao_da_thread, args=("minha thread "+str(c), ))
        t.start()
        c+=1