/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ex003;

/**
 *
 * @author laboratorio
 */
public class TelaThread extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public TelaThread() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JlabelT1 = new javax.swing.JLabel();
        JlabelT3 = new javax.swing.JLabel();
        JlabelT2 = new javax.swing.JLabel();
        Jstart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JlabelT1.setText("Thread 1");

        JlabelT3.setText("Thread 3");

        JlabelT2.setText("Thread 2");

        Jstart.setText("Start");
        Jstart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JstartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JlabelT2)
                            .addComponent(JlabelT3)
                            .addComponent(JlabelT1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Jstart)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(JlabelT1)
                .addGap(18, 18, 18)
                .addComponent(JlabelT2)
                .addGap(18, 18, 18)
                .addComponent(JlabelT3)
                .addGap(36, 36, 36)
                .addComponent(Jstart)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JstartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JstartActionPerformed
        //  int c=0;    //preso no laço que nunca iria acabar
        //  while(true){
        //      JlabelT1.setText("t1" + c);
        //      c++;
        //  }

        //  for(int c=0; c<1000000; c++){
        //      JlabelT1.setText("t1" + c);
        //  }
        Thread t1 = new Thread() {
            public void run() {
                int c = 0;
                while (true) {
                    c++;
                    JlabelT1.setText("t1:" + c);
                }
            }
        };
        Thread t2 = new Thread() {
            public void run() {
                int c = 0;
                while (true) {
                    c++;
                    JlabelT2.setText("t2:" + c);
                }
            }
        };
        Thread t3 = new Thread() {
            public void run() {
                int c = 0;
                while (true) {
                    c++;
                    JlabelT3.setText("t3:" + c);
                }
            }
        };
        //susgestões de pripriedade em S.O.
        t1.setPriority(1);//prioriedade minima
        t2.setPriority(5);//prioriedade media
        t3.setPriority(10);//prioriedade maxima

        t1.start();
        t2.start();
        t3.start();
        //finaliza o onclick
    }//GEN-LAST:event_JstartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaThread().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlabelT1;
    private javax.swing.JLabel JlabelT2;
    private javax.swing.JLabel JlabelT3;
    private javax.swing.JButton Jstart;
    // End of variables declaration//GEN-END:variables
}
